# Numpy and SciPy Handson

In [2]:
import numpy as np

1.How to compare two NumPy arrays?

In [4]:
list_num1 = np.array([10, 20, 30])
list_num2 = np.array([10, 24, 30])
print(np.array_equal(list_num1,list_num2))


False


In [7]:
a = np.array([10, 20, 30])
b = np.array([10, 24, 30])
c = a == b
var = c.all()
print(var)


False


#2.How to check whether specified values are present in NumPy array?

In [8]:
a=np.array([[1,2,3,4,5,6],[9,10,11,12,8,5]])
print("Original List\n",a)

print(2 in a)
print(13 in a)


[[ 1  2  3  4  5  6]
 [ 9 10 11 12  8  5]]
True
False


In [9]:
a  = np.array([1,2,3,4,5])

print(np.isin(a,[2]))

[False  True False False False]


3.How do you concatenate two NumPy arrays vertically and horizontally?

In [14]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print("Original a\n",a)
print("Original b\n",b)
print("Array vertically concatenated\n",np.vstack((a,b)))
print("Array horizontally concatenated\n",np.hstack((a,b)))

Original a
 [[1 2]
 [3 4]]
Original b
 [[5 6]
 [7 8]]
Array vertically concatenated
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Array horizontally concatenated
 [[1 2 5 6]
 [3 4 7 8]]


4.How do you sort a NumPy array in ascending and descending order?

In [16]:
a = np.array([1,5,9,3,5,6])

b = np.sort(a)
print("Ascending Order" , b)

c = np.sort(a)[::-1]
print("Descending", c)

Ascending Order [1 3 5 5 6 9]
Descending [9 6 5 5 3 1]


In [18]:
a = np.array([1,5,9,3,5,6])

idx = np.argsort(a)

print(idx)

b = a[idx[::-1]]
print(b)

[0 3 1 4 5 2]
[9 6 5 5 3 1]


5.How do you perform element-wise mathematical operations on two NumPy arrays?

In [20]:
a = np.array([10, 20, 30])
b = np.array([101, 24, 45])

c = a + b
print(c)

d = a / b
print(d)

[111  44  75]
[0.0990099  0.83333333 0.66666667]


6.Write a NumPy program to find the k smallest values of a given NumPy array.

In [25]:
k = int(input("Enter the value of k"))

arr = np.array([23, 14, 15, 31, 24, 51, 67])
print(arr)

arr1 = np.sort(arr)
print("Sorted Array\n",arr1)
  
print(k, "smallest elements of the array are")
print(arr1[:k])

Enter the value of k4
[23 14 15 31 24 51 67]
Sorted Array
 [14 15 23 24 31 51 67]
4 smallest elements of the array are
[14 15 23 24]


7.Write a NumPy program to create an array of the integers from 10 to 50 and print only the values that are divisible by 3.

In [38]:
import numpy as np

num = np.arange(10,51)

len1 = len(num)

for i in range(len1):
    if num[i]%3 == 0:
        print(num[i])


12
15
18
21
24
27
30
33
36
39
42
45
48


In [33]:
arr = np.arange(10,51)
div = arr[arr % 3 == 0]
print(div)

[12 15 18 21 24 27 30 33 36 39 42 45 48]


8.Write a NumPy program to create a 2D array with 1 on the border and 0 inside.

In [43]:
x = np.ones((5,5))
print(x)

x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
l1 = [1,2,3,4,5,6]
l1[1:-1]

9.Write a program to find Permutation and Combination for for a given value.

In [39]:
from scipy.special import comb,perm

In [41]:
n = int(input("Enter the value of n: "))
r = int(input("Enter the value of r: "))
permutation = perm(n,r)
combination = comb(n,r)
print(f'Permutation of {n} and {r} = {permutation}')
print(f'Combination of {n} and {r} = {combination}')


Enter the value of n: 10
Enter the value of r: 5
Permutation of 10 and 5 = 30240.0
Combination of 10 and 5 = 252.0
